/**
 * What exactly 80 KB looks like.
 *
 * Every image on this page is the engine's own output, generated by
 * `pnpm build:gallery` and committed — including the numbers, which come from
 * the same run. Nothing here is hand-tuned, and a change to the engine changes
 * this page.
 */

import Link from 'next/link';
import type { Metadata } from 'next';
import GallerySample, { type Sample } from '@/components/GallerySample';
import samples from './samples.json';

export const metadata: Metadata = {
  title: 'Gallery',
  description:
    'Four images at exactly 80,000 bytes, next to their originals: a photograph, a screenshot, an illustration and a transparent graphic.',
};

export default function Gallery() {
  const { samples: entries, generated } = samples as unknown as {
    samples: Sample[];
    generated: string;
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="mx-auto max-w-3xl px-4 py-10">
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">
            ← Exact80
          </Link>
          <h1 className="mt-4 text-3xl font-bold tracking-tight">What 80 KB looks like</h1>
          <p className="mt-3 max-w-2xl text-muted-foreground">
            Four kinds of image, each at exactly 80,000 bytes, next to the original. Drag the
            divider. These are the engine&apos;s own output — same code the site runs, numbers from
            the same run — so if the engine gets worse, this page does too.
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-3xl space-y-8 px-4 py-8">
        {entries.map((sample) => (
          <GallerySample key={sample.slug} sample={sample} />
        ))}

        <section className="border-t border-border pt-8 text-sm text-muted-foreground">
          <p>
            The photograph is the interesting case: it carries far more detail than the budget
            holds, so the search spends the bytes on a smaller, cleaner image rather than a
            full-size smear. The transparent graphic is the one where the formats part company —
            AVIF keeps the alpha channel at full size, WebP has to give up resolution to afford it.
          </p>
          <p className="mt-3">
            Generated {new Date(generated).toLocaleDateString('en-GB', { dateStyle: 'long' })} by{' '}
            <code className="font-mono">pnpm build:gallery</code>.
          </p>
        </section>
      </main>
    </div>
  );
}
